language: node_js
os: linux

node_js:
  - "stable"

cache:
  directories:
    - node_modules

notifications:
  slack: bioprimeworkspace:$SLACK_TOKEN

before_install:
  - npm i -g npm@5.1.0

script:
  - npm test
  - npm build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/frontend:latest -t $DOCKER_USERNAME/frontend:$TRAVIS_JOB_NUMBER .
  - docker push $DOCKER_USERNAME/frontend:latest
  - docker push $DOCKER_USERNAME/frontend:$TRAVIS_JOB_NUMBER
