language: node_js
os: linux

node_js:
  - "stable"

cache:
  directories:
    - node_modules

notifications:
  slack: bioprimeworkspace:PeSqLEmvdR8KucSYVLSPBzWU

before_install:
  - npm i -g npm@5.1.0

script:
  - npm test
  - npm build
