export default {
  orientations: ["Forward", "Reverse"],
  organism: [
    "Escherichia coli TG1",
    "Escherichia coli WK6",
    "Homo sapiens",
    "Mus musculus",
    "Rattus norvegicus domestica",
    
  ],
  humanGenomBuild: [
    "NCBI Build 34",
    "NCBI Build 35",
    "NCBI Build 36.1",
    "GRCh37",
    "GRCh38",
  ],
  positionInReference: [
    "5'-promotor",
    "5'-untranslated region",
    "3'-untranslated region",
    "5'-exon",
    "3'-exon",
    "5'-intron",
    "3'-intron",
    "5'-enhancer",
    "5'-up",
    "3'-dw",
    "Intergenic",
    "No data",
  ],
  formulation: [
    "Lyophilized",
    "Water",
    "Resuspended in TRIS",
    "Resuspended in 1x TE",
    "Resuspended in 0.1 X TE",
    
  ],
  storingT: ["Room temperature", "+4", "-20", "-80"],
  purificationMethod: [
    "Cartridge",
    "Desalted",
    "HPLC",
    "HPLC X",
    "PAGE",
    
  ],
  threeQuencher: ["MGBNFQ", "TAMRA", "QSY"],
  fiveDye: ["GFAM", "VIC", "TET", "NED", "ABY"],
  typeOfPrimer: [
    "GAPDH primer",
    "M13 primer",
    "M13/pUC primer",
    "miRNA primer",
    "DNA/RNA probe",
    "TaqProbe",
    "Random primer",
    "Oligo dT",
    "RNA probes",
    "SP6 probes",
    "T3 primer",
    "T7 primer",
    "Gene Specific primer",
    "Disease Specific primer",
    "Region Specific primer",
    "Gene Fusion primer",
    "Break Apart primer",
    "Chromosome Control primer",
  ],
  size: ["XS", "S", "M", "L"],
  fiveModification: [
    "FAM",
    "HEX",
    "ROX",
    "VIC",
    "T(JOE)",
    "T(ROX)",
    "Aldehyde Modifier",
    "Aleza Fluor 488",
    "Aleza Fluor 532",
    "Aleza Fluor 546",
    "Aleza Fluor 555",
    "Aleza Fluor 594",
    "Aleza Fluor 647",
    "Aleza Fluor 660",
    "Aleza Fluor 750",
    "Alkaline Phospates",
    "Amino C12",
    "Amino Linker C6",
    "BHQ-0",
    "BHQ-1",
    "BHQ-2",
    "BHQ-3",
    "Biotin",
    "Biotin TEG",
    "BODIPY 493/503",
    "BODIPY 530/550",
    "BODIPY 558/568",
    "BODIPY 564/570",
    "BODIPY 576/589",
    "BODIPY 581/591",
    "BODIPY 630/650-X",
    "BODIPY 650/655-X",
    "BODIPY FL",
    "BODIPY FL-X",
    "BODIPY R6G",
    "BODIPY TMR-x",
    "BODIPY TR-X",
    "CAL Fluor Gold 540",
    "CAL Fluor Orange 560",
    "CAL Fluor Red 590",
    "CAL Fluor Red 610",
    "CAL Fluor Red 635",
    "CIV-550",
    "DABCYL",
    "Fluorescein",
    "Horseradish Peroxidase",
    "Marina BlueTM",
    "Oregon Green 488",
    "Oregon Green 488-X",
    "Oregon Green 500",
    "Oregon Green 514",
    "Pacific BlureTM",
    "Phos",
    "Phosphate",
    "Quasar 570",
    "Quasar 670",
    "Quasar 705",
    "Rhodamine GreenTM",
    "Rhodamine Red-X",
    "Rhodol Green",
    "Spacer 18",
    "T(BHQ-1)",
    "T(BHQ-2)",
    "T(C6-Amino)",
    "T(Methylene Blue)",
    "TAMRA",
    "TET",
    "Texas Red-X",
    "Thiol",
    "None",
    
  ],
  threeModification: [
    "Amino Linker C7",
    "BHQ-0",
    "BHQ-1",
    "BHQ-2",
    "BHQ-3",
    "Biosearch Blue",
    "Biotin",
    "Biotin TEG",
    "C3-Fluorescein",
    "CAL Fluor Orange 560",
    "CAL Fluor Red 610",
    "d-Uridine",
    "DABCYL",
    "mdC(ROX)",
    "mdC(TEG-Amino)",
    "Methylen Blue",
    "Phos",
    "Phosphate",
    "Pulsar 650",
    "Quasar 570",
    "Quasar 670",
    "Quasar 705",
    "Spacer 6",
    "Spacer C3",
    "T(C6-Amino)",
    "T(C6-Biotin)",
    "T(CAL Fluor Gold 540)",
    "T(CAL Fluor Orange 560)",
    "T(CAL Fluor Red 590)",
    "T(CAL Fluor Red 610)",
    "T(CAL Fluor Red 635)",
    "T(Methylene Blue)",
    "TAMRA",
    "Thiol C6 SS",
    "None",
    
  ],
  project: [],
  primerApplication: [
    "Genotyping",
    "Cloning",
    "NGS",
    "Sanger Sequencing",
    "Bisulfite converted",
    "cDNA synthesis",
    "RT-qPCR-SYBR",
    "RT-qPCR-TaqMan",
    "PCR",
    "ddPCR",
    "Methylation-specific PCR",
    "In situ hybridisation",
    "FISH",
    "ChIP",
    "Flow Cytometry",
    
  ],
  concentrationOrderedUnit: [
    {
      value: "NANOMOL",
      label: "nmol",
    },
    {
      value: "MIKROM",
      label: "µM",
    },
    {
      value: "NANOM",
      label: "nM",
    },
  ],
  amountAvailablePackType: [
    {
      value: "TUBE",
      label: "Tube",
    },
    {
      value: "PLATE",
      label: "Plate",
    },
  ],
  amountAvailableVolume: ["µl", "number of wells"],
  checkSpecificityBlast: ["Yes", "No"],
  // list of designerNames must be acquired from database
  //  designerName : [],
  // list of project names must be acquired from database
  //  projects : [],
  supplier: ["Kemomed", "MikroPolo", "Omega"],
  roles: ["ADMIN","TECHNICIAN","RESEARCHER","GUEST"],
  manufacturer: [
    "Biocompare",
    "BioSearch",
    "CustomArray",
    "Genewiz",
    "Integrated DNA Technologies",
    "Sigma-Aldrich",
    "ThermoFisher Scientific",
    
  ],
  currentUser: "test",
  // list of freezers, drawers, boxes must be acquired from database
  freezer: [],
  drawer: [],
  box: [],
  defaultPrimerData: {
    sequence: "",
    tm: "",
    gcpercent: "",
    optimalTOfAnnealing: "",
    lengthOfAmplicone: "",
    amountAvailablePackType: "",
    amountAvailablePacks: "",
    amountAvailable: "",
    concentrationOrdered: "",
    concentrationOrderedUnit: "",
    typeOfPrimer: "",
  },
  defaultUserData: {
    name: "",
    username: "",
    role: "",
    password: "",
    workTitle: "",
    usernames: "s",
  },
  requiredOld: ["name","sequence","organism","gen","ncbiGenId","positionInReference","typeOfPrimer","fiveModification","threeModification","formulation","freezer","drawer","box","primerApplication"],
  requiredNew: ["name","sequence","organism","gen","ncbiGenId","positionInReference","typeOfPrimer","fiveModification","threeModification","formulation","freezer","drawer","box","primerApplication","concentrationOrdered","amountAvailable","amountAvailablePackType"],
  requiredOrderedToReceived: ["packType","amountAvailable","freezer","drawer","box","project"],
};
